/* Ten local learning experiments. All computations run in the browser. */
const ACTIVITIES=[
 {question:'If six apps are open but the classroom computer has space for four active apps, what happens?',choices:['Everything stays in RAM','Some work must be moved or apps slowed','The SSD becomes the CPU'],correct:1,why:'RAM is limited working space. When active work exceeds it, the system may move some data to slower storage, which can reduce responsiveness.',challenge:'Why would saving a document to an SSD still matter after closing every app?',control:'Open apps',min:1,max:8,start:3,unit:'apps',compute:v=>({label:v<=4?'Fits in RAM':'Exceeds RAM capacity',detail:v<=4?`${v} active app${v===1?'':'s'} fit in this model’s four slots.`:`${v} apps need ${v-4} more slots than this model has. The operating system must manage the shortage.`,view:`RAM slots: ${'●'.repeat(Math.min(v,4))}${'○'.repeat(4-Math.min(v,4))}  ${v>4?'→ overflow: '+(v-4):''}`})},
 {question:'Which change made computers much smaller and more energy efficient than vacuum-tube machines?',choices:['Transistors','Bigger keyboards','More paper storage'],correct:0,why:'Transistors replaced many vacuum tubes and enabled smaller, more reliable electronic circuits.',challenge:'Why does a timeline show broad eras rather than one exact date for every computer?',control:'Computing era',options:['Mechanical','Vacuum tubes','Transistors','Integrated circuits','Microprocessors'],compute:v=>({label:v,detail:({Mechanical:'Mechanical devices performed calculations through moving parts.', 'Vacuum tubes':'Electronic switching worked but required substantial space and power.',Transistors:'Semiconductor switches greatly reduced size and power use.','Integrated circuits':'Many electronic components were placed on one chip.',Microprocessors:'A processor on a chip helped make personal and mobile computing practical.'})[v],view:`Development: Mechanical → Tubes → Transistors → ICs → Microprocessors`})},
 {question:'If you change a heading style, what happens to all headings using that style?',choices:['They update together','Only the first heading changes','The document deletes its images'],correct:0,why:'Styles define reusable formatting. Changing one style can update every paragraph that uses it.',challenge:'When would applying a style be more useful than making one word bold?',control:'Heading size',min:18,max:38,start:25,unit:'px',compute:v=>({label:`Heading style: ${v}px`,detail:'Both sample headings use the same style. Moving the control updates both consistently.',view:`<span style="font-size:${v}px">Section A</span> &nbsp; <span style="font-size:${v}px">Section B</span>`})},
 {question:'Which slide is usually easier to explain from the back of a classroom?',choices:['One main idea and a clear visual','Ten small paragraphs','Tiny text in every corner'],correct:0,why:'A clear main idea and readable visual help the audience follow the speaker.',challenge:'How would you split a crowded slide without losing its key message?',control:'Lines on slide',min:1,max:10,start:4,unit:'lines',compute:v=>({label:v<=4?'Easy to scan':v<=7?'Getting crowded':'Very dense',detail:`This simplified slide has ${v} text lines. Readability also depends on font size, contrast and the room.`,view:'▰ '.repeat(v)})},
 {question:'If the value in A1 changes, what should happen to a formula =A1+B1?',choices:['It recalculates','The formula turns into plain text','B1 disappears'],correct:0,why:'A spreadsheet formula refers to cells and recalculates when the referenced values change.',challenge:'What would =A1+B1 show when A1 is 7 and B1 is 5?',control:'A1 value (B1 = 5)',min:0,max:20,start:7,unit:'',compute:v=>({label:`C1 = ${v+5}`,detail:`A1 = ${v}; B1 = 5; C1 contains =A1+B1, so ${v}+5=${v+5}.`,view:`A1 [${v}]  +  B1 [5]  →  C1 [${v+5}]`})},
 {question:'What must a browser usually learn before it can contact a website by domain name?',choices:['Its IP address from DNS','The screen brightness','The CPU temperature'],correct:0,why:'DNS helps resolve a domain name to an IP address. The browser can then contact a server; HTTPS adds encrypted transport.',challenge:'Why does HTTPS protect message contents but not mean every website is trustworthy?',control:'Connection step',options:['DNS lookup','Connect to server','HTTPS/TLS','Response'],compute:v=>({label:v,detail:({'DNS lookup':'The browser asks a resolver for the address associated with a domain.','Connect to server':'Packets travel through networks to the server address.','HTTPS/TLS':'The browser and server establish an encrypted connection when using HTTPS.','Response':'The server sends data; the browser interprets and displays it.'})[v],view:'Browser → DNS → Network → Server → Browser'})},
 {question:'For an AND gate, what is the output when A = 1 and B = 0?',choices:['0','1','2'],correct:0,why:'AND outputs 1 only when both inputs are 1.',challenge:'Which gate outputs 1 when exactly one input is 1?',control:'Logic gate',options:['AND','OR','XOR'],compute:v=>({label:`${v} truth table`,detail:({'AND':'AND needs both inputs to be 1.','OR':'OR needs at least one input to be 1.','XOR':'XOR needs exactly one input to be 1.'})[v],view:[0,1].flatMap(a=>[0,1].map(b=>`${a} ${v} ${b} = ${v==='AND'?(a&b):v==='OR'?(a|b):(a^b)}`)).join('  |  ')})},
 {question:'If a router fails, can two PCs connected to the same working switch still communicate locally?',choices:['Yes, if their local links work','No, all local links vanish','Only if a printer is on'],correct:0,why:'The switch can still forward local traffic. The failed router prevents traffic between that LAN and other networks.',challenge:'What changes if the central switch fails instead of the router?',control:'Device to disconnect',options:['None','Router','Switch','One PC link'],compute:v=>({label:v==='None'?'All paths available':`${v} disconnected`,detail:({'None':'Local PCs and Internet paths are available in this simplified topology.','Router':'The PCs can still talk through the switch, but cannot reach the Internet through this router.','Switch':'The PCs lose their shared local connection through the switch.','One PC link':'One PC loses this link; the other PC can still reach the router.'})[v],view:`PC A ── Switch ── Router ── Internet  |  PC B ── Switch`})},
 {question:'Can a program run successfully and still give the wrong answer?',choices:['Yes, from a logic error','No, running proves correctness','Only when offline'],correct:0,why:'A logic error can produce an incorrect result even when the syntax is valid and the program runs.',challenge:'Which test input would expose an area formula that adds width and height?',control:'Code example',options:['Correct: area = w * h','Syntax: area = w *','Logic: area = w + h'],compute:v=>({label:v.startsWith('Correct')?'Runs and calculates area':v.startsWith('Syntax')?'Parsing stops':'Runs, but result is wrong',detail:v.startsWith('Correct')?'For w=3 and h=4, the result is 12.':v.startsWith('Syntax')?'An incomplete expression cannot be parsed as this program.':'For w=3 and h=4, this returns 7 rather than the correct area 12.',view:'Source → Parse → Check → Execute → Test'})},
 {question:'If a model trains only on red apples, is its prediction about a green apple dependable?',choices:['Not necessarily; training data is limited','Always, because it has seen apples','The colour cannot affect a model'],correct:0,why:'A narrow training set can teach misleading patterns. Test on varied examples to see whether the model generalizes.',challenge:'What new examples would you add to reduce colour bias in this fruit classifier?',control:'Green apples in training set',min:0,max:6,start:0,unit:'examples',compute:v=>({label:v===0?'Green apple may be misclassified':'Model has diverse apple examples',detail:v===0?'This toy nearest-colour classifier saw only red apples and orange oranges; it may associate green with the wrong class.':`Adding ${v} green apple example${v===1?'':'s'} gives it evidence that apples can also be green. Real models require much broader testing.`,view:`Training: red apples × 6  •  green apples × ${v}  •  oranges × 6`})}
];
const activityAnswers={};
const activityValues={};
function renderActivity(index){const a=ACTIVITIES[index],box=document.getElementById('activity');if(!box)return;const answer=activityAnswers[index];box.innerHTML=`<h2>🧪 Predict → Try → Explain</h2><p class="activity-prompt"><b>Predict:</b> ${a.question}</p><div class="activity-choices">${a.choices.map((v,n)=>`<button type="button" class="activity-choice${answer===n?' picked':''}" onclick="predictActivity(${index},${n})">${v}</button>`).join('')}</div><div id="activity-feedback" class="activity-feedback" aria-live="polite"></div><div id="activity-try" class="activity-try" ${answer===undefined?'hidden':''}><h3>Try it</h3><label for="activity-input">${a.control}</label><div id="activity-control"></div><div id="activity-result" class="activity-result" aria-live="polite"></div><p><b>Explain:</b> ${a.why}</p><p><b>Apply it:</b> ${a.challenge}</p></div>`;if(answer!==undefined){showActivityFeedback(index,answer);setupActivityControl(index)}}
function predictActivity(index,choice){activityAnswers[index]=choice;renderActivity(index);window.notifyActivityChange?.(index)}
function showActivityFeedback(index,choice){const a=ACTIVITIES[index],f=document.getElementById('activity-feedback');f.className='activity-feedback '+(choice===a.correct?'correct':'retry');f.textContent=(choice===a.correct?'✅ Good prediction. ':'💡 Reconsider the idea. ')+a.why}
function setupActivityControl(index){const a=ACTIVITIES[index],c=document.getElementById('activity-control');if(a.options){const select=document.createElement('select');select.id='activity-input';for(const option of a.options){const item=document.createElement('option');item.value=option;item.textContent=option;select.appendChild(item)}c.appendChild(select);select.value=activityValues[index]??a.options[0];select.addEventListener('change',()=>updateActivity(index,select.value));updateActivity(index,activityValues[index]??a.options[0])}else{const slider=document.createElement('input');slider.id='activity-input';slider.type='range';slider.min=a.min;slider.max=a.max;slider.value=a.start;c.appendChild(slider);slider.value=activityValues[index]??a.start;slider.addEventListener('input',()=>updateActivity(index,Number(slider.value)));updateActivity(index,activityValues[index]??a.start)}}
function updateActivity(index,value){activityValues[index]=value;window.notifyActivityChange?.(index);const result=ACTIVITIES[index].compute(value),box=document.getElementById('activity-result');box.innerHTML=`<strong>${result.label}</strong><div class="activity-model"></div><p></p>`;box.querySelector('.activity-model').innerHTML=result.view;box.querySelector('p').textContent=result.detail}

function applyRemoteActivity(index,answer,value){if(!Number.isInteger(index)||index<0||index>=ACTIVITIES.length)return;if(Number.isInteger(answer)&&answer>=0&&answer<ACTIVITIES[index].choices.length)activityAnswers[index]=answer;else delete activityAnswers[index];if(value!==undefined){const a=ACTIVITIES[index];if(a.options&&a.options.includes(value))activityValues[index]=value;else if(!a.options&&Number.isFinite(value))activityValues[index]=Math.max(a.min,Math.min(a.max,value))}renderActivity(index);const ctl=document.getElementById('activity-input');if(ctl&&activityValues[index]!==undefined){ctl.value=activityValues[index];updateActivity(index,activityValues[index])}}
