/* Local, accessible image-and-text charts for every teaching note. */
const CHART_HISTORY=[
 {year:'Early counting',image:'abacus.jpg',file:'Schoty abacus.jpg',caption:'A later Russian abacus illustrates physical counting tools; it is not an ancient artifact.'},
 {year:'c. 1642',image:'pascaline.jpg',file:'Pascaline calculator.jpg',caption:'The Pascaline illustrates an early mechanical calculator.',source:'https://www.computerhistory.org/revolution/calculators/1/45'},
 {year:'1847–1849',image:'difference-engine.jpg',file:'Difference Engine No. 2.jpg',caption:'Modern reconstruction of Babbage’s Difference Engine No. 2 design, with Ada Lovelace’s portrait below.',source:'https://www.computerhistory.org/babbage/engines/' ,extra:{image:'lovelace.jpg',file:'Ada Lovelace portrait.jpg',caption:'Portrait of Ada Lovelace, whose writing explored what programmable machines might do.'}},
 {year:'1946',image:'history.jpg',file:'Classic shot of the ENIAC.jpg',caption:'ENIAC illustrates vacuum-tube era computers.',source:'https://www.computerhistory.org/timeline/1946/'},
 {year:'1947',image:'transistor.jpg',file:'1st-Transistor.jpg',caption:'The first point-contact transistor at Bell Labs. Photo: Wikimedia Commons, CC BY-SA 3.0.',source:'https://www.computerhistory.org/siliconengine/invention-of-the-point-contact-transistor/'},
 {year:'Integrated circuits',image:'microprocessor.jpg',file:'C4004 (Intel).jpg',caption:'The 1971 Intel 4004 is a later integrated circuit example, not the first integrated circuit.'},
 {year:'1971',image:'microprocessor.jpg',file:'C4004 (Intel).jpg',caption:'Intel 4004, an early commercial single-chip microprocessor.',source:'https://www.computerhistory.org/siliconengine/microprocessor-integrates-cpu-function-onto-a-single-chip/'},
 {year:'Personal computers',image:'computer.jpg',file:'Xbox-Motherboard-Rev1.jpg',caption:'A modern motherboard used as a comparison with earlier personal computers.'},
 {year:'1969 → 1989',image:'network.jpg',file:'1969 ARPANET BBN IMP.jpg',caption:'ARPANET equipment illustrates an Internet precursor; the Web was proposed in 1989.',source:'https://home.cern/science/computing/the-birth-of-the-web/short-history-web/'},
 {year:'Review timeline',image:'history.jpg',file:'Classic shot of the ENIAC.jpg',caption:'Use this historical image to compare machine size, components and purpose across eras.'}
];
let chartScale=1;
function chartEscape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chartMedia(item){const link='https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(item.file);return `<figure class="chart-figure"><div class="chart-image"><img src="assets/${chartEscape(item.image)}" alt="${chartEscape(item.caption)}" loading="lazy"></div><figcaption>${chartEscape(item.caption)} <a href="${link}" target="_blank" rel="noopener noreferrer">Image source and license ↗</a></figcaption></figure>`}
function chartSetZoom(delta){chartScale=Math.min(2.2,Math.max(.8,Math.round((chartScale+delta)*10)/10));chartApplyZoom()}
function chartResetZoom(){chartScale=1;chartApplyZoom()}
function chartApplyZoom(){const root=document.getElementById('conceptCharts');if(!root)return;root.style.setProperty('--chart-zoom',String(chartScale));const out=document.getElementById('chartZoomValue');if(out)out.textContent=Math.round(chartScale*100)+'%';root.querySelector('[data-zoom-out]')?.toggleAttribute('disabled',chartScale<=.8);root.querySelector('[data-zoom-in]')?.toggleAttribute('disabled',chartScale>=2.2)}
function chartRender(){const box=document.getElementById('chartList');if(!box)return;const topic=i,lesson=L[topic],primary=PHOTO_FILES[topic];box.innerHTML=lesson.sections.map(([title,explanation],j)=>{const historical=topic===1?CHART_HISTORY[j]:null;const media=historical||{image:primary[2],file:primary[0],caption:primary[1]};const guide=historical?.source?`<a class="chart-source" href="${chartEscape(historical.source)}" target="_blank" rel="noopener noreferrer">Historical reference ↗</a>`:'';const extra=historical?.extra?chartMedia(historical.extra):'';const schematic=topic===1?'':`<div class="chart-schematic" role="img" aria-label="${chartEscape(lesson.title)} overview diagram">${lesson.image1}</div>`;return `<details class="chart-item"><summary><span class="chart-index">${j+1}</span><span>${chartEscape(title)}</span><span class="chart-chevron" aria-hidden="true">⌄</span></summary><div class="chart-content">${historical?`<strong class="chart-date">${chartEscape(historical.year)}</strong>`:''}<div class="chart-media">${chartMedia(media)}${extra}</div><p class="chart-explanation">${chartEscape(explanation)}</p>${schematic}<p class="chart-question"><b>Discuss:</b> Explain ${chartEscape(title)} in your own words and point to something in the image or diagram that helps.</p>${guide}<button type="button" class="chart-explore" onclick="openNoteIn3D(${topic},${j})">🧊 Explore this concept in 3D</button></div></details>`}).join('');chartApplyZoom()}
function chartInit(){const notes=document.querySelector('.notes-under-lab');if(!notes)return;const sec=document.createElement('section');sec.className='card concept-chart';sec.id='conceptCharts';sec.innerHTML='<h2>🖼 Images + Text Charts</h2><p>Open a concept to see its image, explanation and discussion prompt. Use zoom to make the chart readable across the classroom.</p><div class="chart-tools" role="group" aria-label="Chart zoom"><button type="button" data-zoom-out onclick="chartSetZoom(-.2)" aria-label="Zoom chart out">− Zoom out</button><output id="chartZoomValue" aria-live="polite">100%</output><button type="button" data-zoom-in onclick="chartSetZoom(.2)" aria-label="Zoom chart in">+ Zoom in</button><button type="button" onclick="chartResetZoom()">Reset 100%</button></div><div id="chartList"></div>';notes.insertAdjacentElement('afterend',sec);chartRender()}
chartInit();
