/* Dated notes and genuine source-file links. Topic diagrams remain available offline. */
const HISTORICAL_NOTES={
0:[['1966','Semiconductor RAM was in use; SRAM holds a bit as long as power remains.','https://www.computerhistory.org/siliconengine/semiconductor-rams-serve-high-speed-storage-needs/'],['1970–1971','Intel 1103 DRAM marked the shift toward dense semiconductor main memory. DRAM needs periodic refreshing.','https://www.computerhistory.org/siliconengine/mos-dynamic-ram-competes-with-magnetic-core-memory-on-price/']],
1:[['1946','ENIAC was publicly introduced. It used vacuum tubes and filled a room.','https://www.computerhistory.org/timeline/1946/'],['1957','FORTRAN became an influential early high-level language.','https://www.computerhistory.org/timeline/1957/']],
5:[['29 Oct 1969','The first host-to-host ARPANET message was sent. ARPANET was a precursor, not the whole modern Internet.','https://www.computerhistory.org/internethistory/1960s/'],['1973','Vint Cerf and Bob Kahn sketched internetworking ideas that shaped TCP/IP.','https://www.computerhistory.org/timeline/networking-the-web/'],['Jan 1983','ARPANET adopted TCP/IP, a key milestone for the Internet as a network of networks.','https://www.computerhistory.org/internethistory/1980s/'],['Mar 1989','Tim Berners-Lee proposed the World Wide Web at CERN. The Web runs on the Internet; it is not the Internet itself.','https://home.cern/science/computing/the-birth-of-the-web/short-history-web/'],['1990–1991','The first browser and server took shape in 1990; the Web began spreading beyond CERN in 1991.','https://home.cern/science/computing/the-birth-of-the-web/short-history-web/']],
7:[['1969','ARPANET connected early host computers through packet-switching equipment.','https://www.computerhistory.org/timeline/1969/'],['1983','The ARPANET switched to TCP/IP; the Internet continued to grow afterward.','https://www.computerhistory.org/internethistory/1980s/']],
8:[['1957','FORTRAN became available for scientific computing.','https://www.computerhistory.org/timeline/1957/'],['1959–1960','COBOL was developed for business data processing; a committee formed in 1959 and COBOL appeared in 1960.','https://www.computerhistory.org/timeline/1960/'],['1 May 1964','The first BASIC program ran at Dartmouth.','https://www.library.dartmouth.edu/exhibits/sharing-the-computer'],['1972','C developed at Bell Labs during 1969–1973, with a particularly creative period in 1972.','https://www.nokia.com/bell-labs/about/dennis-m-ritchie/chist.html'],['1991','Python had its first public release in February.','https://legacy.python.org/doc/essays/ppt/jpf001/tsld006.htm'],['1995','Java debuted, and JavaScript appeared in a web browser. They are different languages.','https://education.oracle.com/file/general/4955_BriefHistoryOfJava_7.pdf']]};
const PHOTO_FILES=[
 ['Xbox-Motherboard-Rev1.jpg','Real computer motherboard: identify memory and processing hardware.','computer.jpg'],
 ['Classic shot of the ENIAC.jpg','Historical photograph of ENIAC and its operators.','history.jpg'],
 ['Libreoffice-writer.png','Real word-processing interface screenshot.','writer.png'],
 ['Libreoffice-impress.png','Real presentation-software interface screenshot.','presentation.png'],
 ['Libreoffice-calc.png','Real spreadsheet interface screenshot.','spreadsheet.png'],
 ['First Web Server.jpg','Photograph of the computer used as the first Web server.','web.jpg'],
 ['Logic-gate-and-us.svg','Authentic logic-gate schematic; binary is an abstract idea.','logic.svg'],
 ['1969 ARPANET BBN IMP.jpg','Historical image of an ARPANET Interface Message Processor.','network.jpg'],
 ['Python code example.png','Real screenshot of programming code.','programming.png'],
 ['Neural Network.svg','Published neural-network schematic; the model is an abstract structure.','ml.svg']];
function referenceRender(){const box=document.getElementById('referenceGallery');if(!box)return;const lesson=L[i],notes=HISTORICAL_NOTES[i]||[],file=PHOTO_FILES[i],source='https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(file[0]);
 const timeline=notes.length?'<h3>🗓 Verified milestones</h3><div class="ref-timeline">'+notes.map(n=>'<article><strong>'+safeText(n[0])+'</strong><p>'+safeText(n[1])+'</p><a href="'+n[2]+'" target="_blank" rel="noopener">Historical source</a></article>').join('')+'</div>':'';
 const ram=i===0?'<h3>RAM types and their roles</h3><div class="ref-timeline"><article><strong>SRAM</strong><p>Static RAM uses flip-flop circuits and does not require periodic refresh while powered. It is fast and commonly used for processor caches.</p></article><article><strong>DRAM</strong><p>Dynamic RAM stores charge that leaks away, so it must be refreshed. Its density makes it suitable for main memory.</p></article><article><strong>DDR SDRAM</strong><p>Modern desktop and laptop RAM is usually a generation of double-data-rate synchronous DRAM; DDR4 and DDR5 are generations, not alternatives to DRAM.</p></article></div>':'';
 const languages=i===8?'<h3>Programming language milestones</h3><div class="ref-timeline"><article><strong>1957 · FORTRAN</strong><p>Scientific and numerical computing; an early widely used high-level language.</p></article><article><strong>1959–1960 · COBOL</strong><p>A committee formed in 1959; COBOL became a business-focused language in 1960.</p></article><article><strong>1964 · BASIC</strong><p>First programs ran at Dartmouth on 1 May.</p></article><article><strong>1972 · C</strong><p>Developed at Bell Labs during 1969–1973; 1972 was especially important.</p></article><article><strong>1991 · Python</strong><p>First public release in February; commonly used to teach readable code.</p></article><article><strong>1995 · Java and JavaScript</strong><p>Java debuted for portable applications; JavaScript emerged for browser scripting. Similar names do not mean the same language.</p></article></div>':'';
 box.innerHTML='<h2>📷 Real-world reference & history</h2><p>Real source images are included for offline teaching. Abstract ideas use published schematics and original diagrams.</p><div class="ref-photo"><div class="ref-fallback">'+lesson.image1+'</div><img loading="lazy" alt="'+safeText(file[1])+'" src="'+file[2]+'" onload="this.hidden=false" onerror="this.remove()" hidden><div><b>'+safeText(file[1])+'</b><br><a href="'+source+'" target="_blank" rel="noopener">Photo or schematic source and license</a></div></div>'+timeline+ram+languages+'<button type="button" class="ref-jump" onclick="referenceJumpNotes()">↑ Explore teaching notes under the 3D model</button>';
}
function referenceJumpNotes(){document.querySelector('.notes-under-lab')?.scrollIntoView({behavior:'smooth',block:'start'})}
function referenceInit(){let sec=document.getElementById('referenceGallery');if(!sec){sec=document.createElement('section');sec.id='referenceGallery';sec.className='card reference-gallery';const visuals=document.querySelector('.visuals'),studio=document.getElementById('teachingStudio'),anchor=visuals||studio;if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(sec,anchor)}sec.classList.add('card','reference-gallery');referenceRender()}
referenceInit();
