/* One-board teaching studio. The teacher owns state; the board only displays it. */
const STUDIO_CONTENT=[
 {objective:'Trace how input becomes output and distinguish CPU, RAM and storage.',mistake:'RAM and an SSD both store data, but RAM is volatile working memory.',sequence:['A keyboard sends input','The CPU executes instructions','RAM holds active values','The display shows output'],build:['Input','CPU','RAM','Output'],compare:['RAM: active and volatile','SSD: saved and persistent'],exit:['Where is an unsaved document held while you edit it?','Primarily in RAM; save it to persistent storage.','Saying SSD means the learner may confuse working memory with saved files.']},
 {objective:'Place major computing developments in chronological order.',mistake:'A faster device is not necessarily newer without historical evidence.',sequence:['Mechanical calculators','Vacuum-tube computers','Transistor circuits','Microprocessors'],build:['Mechanical','Vacuum tube','Transistor','Microprocessor'],compare:['Vacuum tubes: large and power hungry','Transistors: smaller electronic switches'],exit:['What replaced many vacuum tubes in computer circuits?','Transistors.','Microprocessor alone skips the important transistor transition.']},
 {objective:'Use styles to make documents consistent and revise efficiently.',mistake:'Manual formatting each heading does not automatically keep them consistent.',sequence:['Draft content','Apply heading styles','Review and revise','Export or print'],build:['Draft','Style','Review','Export'],compare:['Manual formatting: repeated edits','Styles: one update can affect many headings'],exit:['Why use heading styles instead of formatting each heading separately?','Styles make repeated headings consistent and easier to update.','A student may see styles as decoration rather than document structure.']},
 {objective:'Design a readable slide and use speaking notes for detail.',mistake:'More tiny text does not make a slide clearer.',sequence:['Choose one message','Add a clear visual','Keep text readable','Explain aloud'],build:['Message','Visual','Readable text','Delivery'],compare:['Dense slide: hard to scan','Focused slide: one idea and readable visual'],exit:['Where should a speaker keep detailed talking points?','In speaker notes.','Putting a full script on the slide confuses presenter support with audience content.']},
 {objective:'Predict how cells, formulas and charts respond to changed data.',mistake:'A cell reference identifies a location, not a web address.',sequence:['Enter data in cells','Write a formula','Recalculate results','Chart the results'],build:['Data','Formula','Result','Chart'],compare:['Typed total: must edit by hand','Formula: recalculates when inputs change'],exit:['What does =SUM(A1:A5) add?','The values in cells A1 through A5.','Answering column B signals a cell-reference misunderstanding.']},
 {objective:'Explain how browser, DNS, server and HTTPS relate.',mistake:'The Web and the Internet are related but not identical.',sequence:['Enter a web address','DNS resolves a name','Browser contacts a server','HTTPS protects the exchange'],build:['Browser','DNS','Server','Response'],compare:['DNS: locates an address','HTTPS: protects communication'],exit:['Does DNS encrypt the webpage?','No. DNS resolves a name; HTTPS protects the web exchange.','The student may have swapped addressing and encryption.']},
 {objective:'Convert small binary values and reason about logic gates.',mistake:'Four bits do not always represent the same number.',sequence:['Read each binary bit','Assign powers of two','Add place values','Check the decimal result'],build:['Bits','Place values','Sum','Decimal'],compare:['AND: both inputs true','OR: at least one input true'],exit:['Why is 1010₂ equal to ten?','8 + 2 = 10.','Counting digits rather than place values misses positional notation.']},
 {objective:'Trace local and remote network paths and predict failures.',mistake:'A router failure does not necessarily stop traffic on a working local switch.',sequence:['PC sends a packet','Switch forwards locally','Router reaches another network','Server replies'],build:['PC','Switch','Router','Internet'],compare:['Working router: local and remote paths','Failed router: local switch traffic can continue'],exit:['Can two PCs on the same working switch communicate if the router fails?','Yes, if their local links and settings still work.','No suggests the learner assumes all traffic must cross the router.']},
 {objective:'Trace source code through translation, execution and testing.',mistake:'A program can run and still contain a logic error.',sequence:['Write source code','Translate or interpret','Run with input','Test expected output'],build:['Source','Translate','Run','Test'],compare:['Syntax error: code cannot be parsed','Logic error: code runs but result is wrong'],exit:['Can a program run successfully but give the wrong answer?','Yes. A logic error may only show up during testing.','No suggests the learner equates execution with correctness.']},
 {objective:'Distinguish training, testing and generalization in machine learning.',mistake:'Perfect training accuracy does not prove a model works on unseen cases.',sequence:['Collect varied examples','Train a model','Test unseen examples','Check errors and bias'],build:['Examples','Train','Test','Evaluate'],compare:['Training score: seen examples','Test score: separate unseen examples'],exit:['Why keep a separate test set?','To evaluate the model on examples it was not trained on.','Using only training data can hide overfitting.']}
];
const STUDIO_DEFAULT=()=>({tour:-1,step:-1,build:[],compare:false,exit:0,spot:'',phase:0,tally:[0,0,0,0],font:1,contrast:false,motion:false});
let studioState=STUDIO_DEFAULT();
const studioBoard=document.body.classList.contains('board');
const safeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const studioStepNames=['Explain','Predict','Demonstrate','Check'];
function studioSet(patch){if(studioBoard)return;studioState={...studioState,...patch};studioRender();if(typeof send==='function')send()}
function studioResetTopic(){studioState={...STUDIO_DEFAULT(),font:studioState.font,contrast:studioState.contrast,motion:studioState.motion};studioRender()}
function studioTourNext(){const scene=getScene(i,modelViews[i]??0),next=(studioState.tour+1)%scene.items.length;studioSet({tour:next});const item=scene.items[next],label=item[6]||item[0];labExplain(label,item[5]||BASE_DETAILS[i][item[0]]||'Explore this component.',next)}
function studioBuildAdd(index){const answer=STUDIO_CONTENT[i].build;if(index<0||index>=answer.length||studioState.build.length>=answer.length)return;studioSet({build:[...studioState.build,index]})}
function studioBuildUndo(){studioSet({build:studioState.build.slice(0,-1)})}
function studioNextStep(){studioSet({step:(studioState.step+1)%STUDIO_CONTENT[i].sequence.length})}
function studioTally(index){const counts=[...studioState.tally];counts[index]++;studioSet({tally:counts})}
function studioSetAccessibility(key,value){studioSet({[key]:value});try{localStorage.setItem('csStudioAccessibility',JSON.stringify({font:studioState.font,contrast:studioState.contrast,motion:studioState.motion}))}catch(e){}}
function studioSpot(mode){studioSet({spot:mode})}
function studioApplyRemote(raw){if(!studioBoard)return;const d=STUDIO_DEFAULT();if(raw&&typeof raw==='object'){
 d.tour=Number.isInteger(raw.tour)&&raw.tour>=-1&&raw.tour<12?raw.tour:-1;
 d.step=Number.isInteger(raw.step)&&raw.step>=-1&&raw.step<4?raw.step:-1;
 d.build=Array.isArray(raw.build)?raw.build.filter(x=>Number.isInteger(x)&&x>=0&&x<4).slice(0,4):[];
 d.compare=raw.compare===true;d.exit=[0,1,2].includes(raw.exit)?raw.exit:0;
 d.spot=['','tour','step','build','compare','exit','recap','mistake','check'].includes(raw.spot)?raw.spot:'';
 d.phase=[0,1,2,3].includes(raw.phase)?raw.phase:0;
 d.tally=Array.isArray(raw.tally)?raw.tally.slice(0,4).map(x=>Number.isInteger(x)&&x>=0&&x<1000?x:0):[0,0,0,0];
 d.font=[1,1.2,1.45].includes(raw.font)?raw.font:1;d.contrast=raw.contrast===true;d.motion=raw.motion===true;
}studioState=d;studioRender()}
function studioRender(){const data=STUDIO_CONTENT[i],panel=document.getElementById('teachingStudio');if(!data||!panel)return;
 document.documentElement.style.setProperty('--board-scale',studioState.font);document.documentElement.style.fontSize=(16*studioState.font)+'px';
 document.body.classList.toggle('classroom-contrast',studioState.contrast);
 document.body.classList.toggle('classroom-still',studioState.motion);
 const scene=getScene(i,modelViews[i]??0),parts=scene.items;
 const tour=studioState.tour>=0&&studioState.tour<parts.length?parts[studioState.tour]:null;
 const tourLabel=tour?(tour[6]||tour[0]):'Tap Next component to begin.';
 const tourDetail=tour?(tour[5]||BASE_DETAILS[i][tour[0]]||'Explore this component.'):'The current 3D model stays interactive.';
 const sequence=data.sequence;
 const build=data.build,chosen=studioState.build,finished=chosen.length===build.length,correct=finished&&chosen.every((v,k)=>v===k);
 const row=(label,body,controls='')=>'<section class="studio-block"><h3>'+label+'</h3>'+body+(studioBoard?'':'<div class="studio-controls">'+controls+'</div>')+'</section>';
 let html='<div class="studio-title"><h2>🎓 Teaching Studio</h2><span> '+studioStepNames[studioState.phase]+' · '+safeText(data.objective)+'</span></div>';
 if(!studioBoard)html+=row('Presentation & lesson pace','<p>Choose what fills the board. The teacher controls remain here.</p>',studioStepNames.map((x,k)=>'<button onclick="studioSet({phase:'+k+'})" '+(k===studioState.phase?'class="active"':'')+'>'+x+'</button>').join('')+['tour','step','build','compare','exit','recap','mistake','check'].map(x=>'<button onclick="studioSpot(\''+x+'\')">Present '+x+'</button>').join('')+'<button onclick="studioSpot(\'\')">Close presentation</button>');
 html+=row('1. Guided 3D tour','<p><b>'+(studioState.tour>=0?'Component '+(studioState.tour+1)+'/'+parts.length+': ':'')+safeText(tourLabel)+'</b> — '+safeText(tourDetail)+'</p>', '<button onclick="studioTourNext()">Next component</button><button onclick="studioSet({tour:-1})">Reset tour</button>');
 html+=row('2. Build the model','<div class="studio-order">'+chosen.map((n,k)=>'<span>'+(k+1)+'. '+safeText(build[n])+'</span>').join('')+(chosen.length===0?'<span>Place the parts in order.</span>':'')+'</div>'+(finished?'<p class="studio-result">'+(correct?'✅ Correct sequence.':'🔎 Try again: check the first incorrect position.')+'</p>':'<p>Choose the next part of the sequence.</p>'),build.map((x,k)=>'<button onclick="studioBuildAdd('+k+')" '+(chosen.includes(k)?'disabled':'')+'>'+safeText(x)+'</button>').join('')+'<button onclick="studioBuildUndo()">Undo</button><button onclick="studioSet({build:[]})">Reset</button>');
 html+=row('3. Step-through animation','<div class="studio-steps">'+sequence.map((x,k)=>'<span class="'+(studioState.step===k?'current':'')+'">'+(k+1)+'. '+safeText(x)+'</span>').join('')+'</div>', '<button onclick="studioNextStep()">Next step</button><button onclick="studioSet({step:-1})">Reset steps</button>');
 html+=row('4. Compare outcomes',studioState.compare?'<div class="studio-pair"><div>'+safeText(data.compare[0])+'</div><div>'+safeText(data.compare[1])+'</div></div>':'<p>Ask students to predict the difference first.</p>', '<button onclick="studioSet({compare:!studioState.compare})">'+(studioState.compare?'Hide':'Show')+' comparison</button>');
 html+=row('5. Exit question',studioState.exit?'<p class="studio-question">'+safeText(data.exit[0])+'</p>'+(studioState.exit===2?'<div class="studio-result">Answer: '+safeText(data.exit[1])+'<br>Look for: '+safeText(data.exit[2])+'</div>':'<p>Give everyone time to answer aloud or on paper.</p>'):'<p>End the lesson with one explanation in the student’s own words.</p>', '<button onclick="studioSet({exit:1})">Show question</button><button onclick="studioSet({exit:2})" '+(studioState.exit!==1?'disabled':'')+'>Reveal answer</button><button onclick="studioSet({exit:0})">Clear</button>');
 const quiz=typeof QUIZ!=='undefined'?QUIZ[i][conceptCheck?.question>=0?conceptCheck.question:0]:null;
 if(!studioBoard)html+=row('6. Tally a show of hands','<p>Ask A, B, C or D. Add each raised hand here; the board shows totals.</p>',[0,1,2,3].map(k=>'<button onclick="studioTally('+k+')">+'+String.fromCharCode(65+k)+'</button>').join('')+'<button onclick="studioSet({tally:[0,0,0,0]})">Clear tally</button>');
 const tallyMax=Math.max(1,...studioState.tally);html+=row('Class responses','<div class="studio-tally">'+studioState.tally.map((n,k)=>'<div><b>'+String.fromCharCode(65+k)+'</b><span style="width:'+Math.max(2,100*n/tallyMax)+'%"></span><strong>'+n+'</strong></div>').join('')+'</div>');
 if(!studioBoard)html+=row('Teacher preparation','<p><b>Goal:</b> '+safeText(data.objective)+'</p><p><b>Likely confusion:</b> '+safeText(data.mistake)+'</p><p><b>Suggested 15-minute flow:</b> 3 min explain · 3 min predict · 5 min demonstrate and compare · 4 min concept check and exit question.</p><p><b>Materials:</b> teacher device, classroom board, and paper or verbal responses. Prepare the six-digit room code only if using the live board connection.</p>');
 if(!studioBoard)html+=row('Display settings','<p>Settings synchronize with the board.</p>','<button onclick="studioSetAccessibility(\'font\',studioState.font===1?1.2:studioState.font===1.2?1.45:1)">Text size: '+studioState.font+'×</button><button onclick="studioSetAccessibility(\'contrast\',!studioState.contrast)">Contrast: '+(studioState.contrast?'High':'Normal')+'</button><button onclick="studioSetAccessibility(\'motion\',!studioState.motion)">Motion: '+(studioState.motion?'Reduced':'Normal')+'</button>');
 panel.innerHTML=html;
 document.querySelectorAll('.world .obj').forEach((el,n)=>{el.classList.toggle('tour-focus',n===studioState.tour);el.classList.toggle('tour-muted',studioState.tour>=0&&n!==studioState.tour)});
 const overlay=document.getElementById('studioSpotlight');if(overlay){const id=studioState.spot;const blocks={tour:'1. Guided 3D tour',step:'3. Step-through animation',build:'2. Build the model',compare:'4. Compare outcomes',exit:'5. Exit question'};let content='';if(blocks[id]){const nodes=[...panel.querySelectorAll('.studio-block')];const found=nodes.find(n=>n.querySelector('h3')?.textContent===blocks[id]);content=found?.innerHTML||''}else if(id==='recap')content=document.getElementById('recap')?.innerHTML||'';else if(id==='mistake')content=document.getElementById('mistake')?.innerHTML||'';else if(id==='check')content=document.getElementById('conceptCheck')?.innerHTML||'';overlay.innerHTML='<div class="spot-head">'+safeText(L[i].title)+' · '+studioStepNames[studioState.phase]+'</div><div class="spot-content">'+content+'</div>';overlay.hidden=!studioBoard||!id}
}
function studioInit(){const container=document.createElement('section');container.className='card teaching-studio';container.id='teachingStudio';const lab=document.querySelector('.lab');if(lab)lab.parentNode.insertBefore(container,lab);const overlay=document.createElement('div');overlay.id='studioSpotlight';overlay.className='studio-spotlight';overlay.hidden=true;document.body.appendChild(overlay);if(!studioBoard)try{const settings=JSON.parse(localStorage.getItem('csStudioAccessibility')||'{}');for(const k of ['font','contrast','motion'])if(settings[k]!==undefined)studioState[k]=settings[k]}catch(e){}studioRender()}
studioInit();
