/* Bilingual textbook lesson for the classroom board.
   English is intentionally simple. Hindi keeps technical words when that is clearer. */
const TEXTBOOK_HI=[
 ['कंप्यूटर की मुख्य बातें और उसके भाग','कंप्यूटर एक इलेक्ट्रॉनिक मशीन है जो निर्देशों के अनुसार काम करती है। यह डेटा लेती है, उस पर काम करती है, परिणाम दिखाती है और जानकारी को सेव भी कर सकती है।',['Input से डेटा कंप्यूटर में आता है।','CPU निर्देशों पर काम करता है।','RAM अभी चल रहे काम को कुछ समय के लिए रखती है।','Storage फाइलों को बाद के लिए रखता है।']],
 ['कंप्यूटर का इतिहास और विकास','आज का कंप्यूटर एक दिन में नहीं बना। गिनती के पुराने साधनों से लेकर ट्रांजिस्टर, चिप, पर्सनल कंप्यूटर, इंटरनेट और मोबाइल तक कई कदमों में इसका विकास हुआ।',['Abacus गिनती का पुराना साधन है।','Transistor ने कंप्यूटर को छोटा और अधिक भरोसेमंद बनाने में मदद की।','Microprocessor ने CPU के मुख्य काम को एक चिप पर लाने में मदद की।','नई तकनीक आने पर पुरानी तकनीक तुरंत खत्म नहीं होती।']],
 ['वर्ड प्रोसेसिंग','Word processor का उपयोग लिखने, सुधार करने, सजाने, सेव करने और दस्तावेज साझा करने के लिए होता है। अच्छा दस्तावेज साफ और पढ़ने में आसान होना चाहिए।',['Heading से दस्तावेज के भाग साफ दिखते हैं।','Styles एक जैसा format रखने में मदद करते हैं।','Spell check उपयोगी है, लेकिन हमें खुद भी पढ़कर जांच करनी चाहिए।','चित्र तभी लगाएँ जब वे बात समझने में मदद करें।']],
 ['प्रेजेंटेशन','Presentation में slides की मदद से किसी विषय को लोगों के सामने समझाया जाता है। हर slide पर मुख्य बात साफ दिखनी चाहिए।',['एक slide पर एक मुख्य विचार रखना आसान होता है।','बड़े और साफ अक्षर दूर से पढ़ने में मदद करते हैं।','चित्र और diagram बात को जल्दी समझा सकते हैं।','Speaker को केवल slide पढ़ने के बजाय बात समझानी चाहिए।']],
 ['स्प्रेडशीट','Spreadsheet rows और columns में डेटा रखती है। Formula की मदद से हम हिसाब कर सकते हैं और chart से संख्या को आसानी से समझ सकते हैं।',['Cell का नाम column और row से बनता है, जैसे A1।','Formula = से शुरू हो सकता है।','Cell की value बदलने पर उससे जुड़ा formula फिर से हिसाब करता है।','Chart डेटा में pattern देखने में मदद करता है।']],
 ['वेब और वेबसाइट','Web पर browser की मदद से websites खोली जाती हैं। Browser server से page मांगता है और मिले हुए data को screen पर दिखाता है।',['URL किसी web address को बताता है।','DNS domain name को IP address से जोड़ने में मदद करता है।','Server website की files भेजता है।','HTTPS connection को सुरक्षित रखने में मदद करता है।']],
 ['बाइनरी और डिजिटल लॉजिक','कंप्यूटर बहुत सी जानकारी को 0 और 1 के रूप में संभालता है। Logic gates इन 0 और 1 पर नियमों के अनुसार काम करते हैं।',['Bit की value 0 या 1 होती है।','8 bits मिलकर एक byte बनाते हैं।','Binary में हर जगह की value 2 की power पर होती है।','AND gate तभी 1 देता है जब दोनों input 1 हों।']],
 ['नेटवर्क और इंटरनेट','Network दो या अधिक devices को आपस में data भेजने देता है। Internet दुनिया भर के बहुत से networks का बड़ा जुड़ाव है।',['Switch एक local network में devices को जोड़ सकता है।','Router अलग networks के बीच data भेजता है।','IP address network पर destination पहचानने में मदद करता है।','Internet और Web एक ही चीज नहीं हैं; Web, Internet पर चलने वाली services में से एक है।']],
 ['प्रोग्रामिंग','Programming में हम कंप्यूटर को काम करने के निर्देश लिखते हैं। Program को छोटे और साफ steps में बनाना समझने और गलती ढूँढने में मदद करता है।',['Source code इंसान के पढ़ने योग्य instructions होते हैं।','Syntax language के लिखने के नियम हैं।','Logic error में program चल सकता है लेकिन answer गलत हो सकता है।','Testing से हम अलग inputs पर program को जांचते हैं।']],
 ['मशीन लर्निंग','Machine learning में कंप्यूटर examples से pattern सीखने की कोशिश करता है और फिर नए data पर prediction देता है।',['Training data से model सीखता है।','अच्छे और अलग-अलग examples जरूरी हैं।','Test data से नए data पर model को जांचा जाता है।','Model का answer हमेशा सही होगा, यह मानना ठीक नहीं है।']]
];

function tbSafe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tbSimpleEnglish(text){return String(text||'').replace(/persistent storage/gi,'storage that keeps data after power is off').replace(/retains information/gi,'keeps information').replace(/communicates results/gi,'shows or gives the result').replace(/substantial heat/gi,'a lot of heat').replace(/hierarchy/gi,'clear order').replace(/appropriately sized/gi,'the right size').replace(/attribution/gi,'credit to the source').replace(/interconnected/gi,'connected').replace(/functionality/gi,'main work')}
function textbookSpeak(lang){if(!('speechSynthesis' in window))return;const root=document.getElementById('textbookBody');if(!root)return;speechSynthesis.cancel();const selector=lang==='hi'?'.tb-hi':'.tb-en',text=[...root.querySelectorAll(selector)].map(x=>x.innerText).join('. ');const u=new SpeechSynthesisUtterance(text);u.lang=lang==='hi'?'hi-IN':'en-IN';u.rate=.88;speechSynthesis.speak(u)}
function textbookRender(topicIndex=0,sectionIndex=0){const root=document.getElementById('textbookBody');if(!root||typeof L==='undefined'||!L[topicIndex])return;const t=L[topicIndex],hi=TEXTBOOK_HI[topicIndex]||['पाठ','इस विषय को आसान शब्दों में समझें।',[]],sections=t.sections||[],n=Math.max(0,Math.min(sectionIndex,sections.length-1)),s=sections[n]||['Overview',t.overview],hpoint=hi[2][n%Math.max(1,hi[2].length)]||hi[1];root.dataset.topic=topicIndex;root.dataset.section=n;root.innerHTML=`
 <div class="tb-head"><div><span class="tb-kicker">Chapter ${topicIndex+1} of ${L.length}</span><h3>${tbSafe(t.title)}</h3><p class="tb-hi">अध्याय: ${tbSafe(hi[0])}</p></div><div class="tb-actions"><button type="button" onclick="textbookSpeak('en')">🔊 Read English</button><button type="button" onclick="textbookSpeak('hi')">🔊 हिंदी सुनें</button></div></div>
 <div class="tb-grid"><nav class="tb-nav" aria-label="Chapter concepts">${sections.map((x,j)=>`<button type="button" class="${j===n?'active':''}" onclick="textbookRender(${topicIndex},${j})">${j+1}. ${tbSafe(x[0])}</button>`).join('')}<button type="button" onclick="textbookRender(${topicIndex},${sections.length-1})">✓ Summary & questions</button></nav>
 <article class="tb-page"><div class="tb-columns"><section class="tb-en"><span class="tb-language">🇬🇧 Simple English</span><h4>${tbSafe(s[0])}</h4><p>${tbSafe(tbSimpleEnglish(s[1]))}</p><div class="tb-box"><b>Easy idea</b><p>${tbSafe(tbSimpleEnglish(t.key))}</p></div></section>
 <section class="tb-hi"><span class="tb-language">🇮🇳 सरल हिंदी</span><h4>${tbSafe(s[0])}</h4><p>${tbSafe(hpoint)}</p><div class="tb-box"><b>आसान बात</b><p>${tbSafe(hi[1])}</p></div></section></div>
 <div class="tb-example"><b>💡 Easy example / आसान उदाहरण</b><p>${topicIndex===0?'Think of RAM like a study table. The books you are using now stay on the table; other books stay in the cupboard (storage).':'Connect this idea with something students use at home, at school, or on a phone. Ask them to explain the idea in their own words.'}</p><p class="tb-hi">${topicIndex===0?'RAM को पढ़ाई की मेज जैसा समझें। अभी काम की चीजें मेज पर रहती हैं और बाकी चीजें अलमारी (Storage) में रहती हैं।':'इस बात को घर, स्कूल या फोन के किसी आसान उदाहरण से जोड़ें। फिर छात्र से इसे अपने शब्दों में समझाने को कहें।'}</p></div>
 <div class="tb-bottom"><div><h4>Remember / याद रखें</h4><ul>${(t.facts||[]).slice(0,4).map(x=>`<li>${tbSafe(tbSimpleEnglish(x))}</li>`).join('')}</ul></div><div><h4>Practice / अभ्यास</h4><p>1. Explain “${tbSafe(s[0])}” in your own words.</p><p class="tb-hi">1. “${tbSafe(s[0])}” को अपने शब्दों में समझाइए।</p><p>2. Give one daily-life example.</p><p class="tb-hi">2. रोज़मर्रा की जिंदगी से एक उदाहरण दीजिए।</p></div></div>
 <div class="tb-page-nav"><button type="button" ${n===0?'disabled':''} onclick="textbookRender(${topicIndex},${Math.max(0,n-1)})">← Previous concept</button><span>${n+1} / ${sections.length}</span><button type="button" ${n===sections.length-1?'disabled':''} onclick="textbookRender(${topicIndex},${Math.min(sections.length-1,n+1)})">Next concept →</button></div></article></div>`}
function textbookSync(){const root=document.getElementById('textbookBody');if(root&&typeof L!=='undefined'&&typeof i!=='undefined'&&Number.isInteger(i))textbookRender(i,0)}
(function textbookInit(){const main=document.querySelector('main');if(!main)return;let d=document.getElementById('textbookLesson');if(!d){d=document.createElement('details');d.id='textbookLesson';d.className='textbook-lesson card';d.innerHTML='<summary>📖 Textbook Lesson · English + सरल हिंदी <span>tap to open</span></summary><div id="textbookBody"></div>';const drawer=document.getElementById('studioDrawer');if(drawer)main.insertBefore(d,drawer);else main.appendChild(d)}if(!d.dataset.textbookBound){d.addEventListener('toggle',()=>{if(d.open)textbookSync()});d.dataset.textbookBound='1'}const original=window.render;if(typeof original==='function')window.render=function(...args){const out=original.apply(this,args);if(d.open)setTimeout(textbookSync,0);return out}})();
